# Generated by Django 3.1.14 on 2022-05-15 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perguntas', '0002_delete_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=126)),
                ('phone', models.CharField(max_length=11)),
                ('is_whatsapp', models.BooleanField(default=True, verbose_name='É Whatsapp?')),
                ('mensagem', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perguntas.pergunta')),
            ],
            options={
                'db_table': 'comentario',
            },
        ),
    ]
