# Generated by Django 3.2.25 on 2024-11-18 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('comentarios', '0001_initial'), ('comentarios', '0002_alter_comentario_pergunta'), ('comentarios', '0003_alter_comentario_email')]

    initial = True

    dependencies = [
        ('perguntas', '0007_rename_alternativas_alternativa_pergunta'),
        ('perguntas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('is_whatsapp', models.BooleanField(default=True, verbose_name='É Whatsapp?')),
                ('mensagem', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='perguntas.pergunta')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
            },
        ),
    ]
