# Generated by Django 3.1.14 on 2023-04-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
