# Generated by Django 3.2.25 on 2024-05-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_alter_comentario_pergunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
