# Generated by Django 3.1.14 on 2022-12-06 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totalversiculo',
            old_name='livro_id',
            new_name='livro',
        ),
    ]
