# Generated by Django 3.1.14 on 2022-05-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='versao',
            name='sigla',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
