# Generated by Django 3.1.14 on 2023-01-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='sigla',
            field=models.CharField(max_length=4),
        ),
    ]
