# Generated by Django 3.1.14 on 2022-05-11 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblia', '0002_versao_sigla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versao',
            name='sigla',
        ),
    ]
