# Generated by Django 3.2.25 on 2024-11-18 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('perguntas', '0001_initial'), ('perguntas', '0002_alter_tema_id'), ('perguntas', '0003_alter_pergunta_criado_por'), ('perguntas', '0004_auto_20240517_1922'), ('perguntas', '0005_rename_alternativas_corretas_alternativa_correta'), ('perguntas', '0006_remove_pergunta_referencia_biblica'), ('perguntas', '0007_rename_alternativas_alternativa_pergunta'), ('perguntas', '0008_pergunta_referencia_biblica'), ('perguntas', '0009_auto_20240531_1548'), ('perguntas', '0010_pergunta_publicado_status')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enunciado', models.TextField()),
                ('tipo_resposta', models.CharField(choices=[('MES', 'Múltipla Escolha'), ('RCO', 'Referência Completa'), ('RLC', 'Referência Livro-Capítulo'), ('RES', 'Resposta Simples')], max_length=3, verbose_name='Tipo de Resposta')),
                ('referencia', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False, verbose_name='Publicado')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aprovado_status', models.BooleanField(default=False, verbose_name='Revisado')),
                ('aprovado_em', models.DateTimeField(blank=True, null=True)),
                ('publicado_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas_enviadas', to=settings.AUTH_USER_MODEL)),
                ('publicado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perguntas_publicadas', to=settings.AUTH_USER_MODEL)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perguntas_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perguntas.tema')),
                ('recusado_em', models.DateTimeField(blank=True, null=True)),
                ('recusado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perguntas_recusadas', to=settings.AUTH_USER_MODEL)),
                ('recusado_status', models.BooleanField(default=False, verbose_name='Recusado')),
                ('referencia_biblica', models.BooleanField(default=True)),
                ('publicado_status', models.BooleanField(default=False, verbose_name='Publicado')),
            ],
            options={
                'verbose_name': 'Pergunta',
            },
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('correta', models.BooleanField(default=False)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='perguntas.pergunta')),
            ],
        ),
    ]
