# Generated by Django 3.1.14 on 2022-06-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='publicado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='revisado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
