# Generated by Django 3.1.14 on 2023-01-06 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alternativa',
            old_name='alternativas',
            new_name='pergunta',
        ),
    ]
