# Generated by Django 3.1.14 on 2022-05-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='outras_referencias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Publicado'),
        ),
    ]
