# Generated by Django 3.1.14 on 2022-05-11 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblia', '0002_versao_sigla'),
        ('perguntas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=6)),
            ],
            options={
                'verbose_name': 'Grupo',
                'db_table': 'grupo',
            },
        ),
        migrations.RemoveField(
            model_name='referencia',
            name='pergunta',
        ),
        migrations.AddField(
            model_name='pergunta',
            name='outras_referencias',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='perguntas.referencia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pergunta',
            name='refencia_resposta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='referencia_resposta', to='perguntas.referencia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='versiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblia.versiculo', verbose_name='Versículo'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grupo', to='perguntas.grupo'),
            preserve_default=False,
        ),
    ]
