# Generated by Django 3.1.14 on 2022-05-15 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
