# Generated by Django 3.1.14 on 2022-05-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0002_auto_20220511_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Pergunta Status'),
        ),
    ]
