# Generated by Django 3.2.25 on 2024-05-17 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perguntas', '0002_alter_tema_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas_enviadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
