# Generated by Django 3.1.14 on 2022-05-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0002_delete_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Publicado'),
        ),
    ]
