# Generated by Django 3.1.14 on 2022-05-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0003_pergunta_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alternativa',
            old_name='pergunta',
            new_name='alternativas',
        ),
        migrations.RenameField(
            model_name='alternativa',
            old_name='resposta_certa',
            new_name='alternativas_corretas',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='grupo',
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
    ]
