# Generated by Django 3.2.25 on 2024-05-17 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perguntas', '0003_alter_pergunta_criado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='recusado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='recusado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perguntas_recusadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='recusado_status',
            field=models.BooleanField(default=False, verbose_name='Recusado'),
        ),
    ]
