# Generated by Django 3.1.14 on 2022-05-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0003_auto_20220515_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencia',
            options={'verbose_name': 'Referência', 'verbose_name_plural': 'Referências'},
        ),
        migrations.AddField(
            model_name='pergunta',
            name='revisado_status',
            field=models.BooleanField(default=True, verbose_name='Revisado'),
        ),
    ]
