# Generated by Django 3.1.14 on 2022-05-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0004_auto_20220516_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='publicado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='revisado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='revisado_status',
            field=models.BooleanField(default=False, verbose_name='Revisado'),
        ),
    ]
