# Generated by Django 3.2.25 on 2024-05-28 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0004_auto_20240517_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alternativa',
            old_name='alternativas_corretas',
            new_name='correta',
        ),
    ]
