# Generated by Django 3.2.25 on 2024-05-28 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0005_rename_alternativas_corretas_alternativa_correta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='referencia_biblica',
        ),
    ]
