# Generated by Django 3.2.25 on 2024-05-28 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0006_remove_pergunta_referencia_biblica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alternativa',
            old_name='alternativas',
            new_name='pergunta',
        ),
    ]
