# Generated by Django 3.2.25 on 2024-05-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0007_rename_alternativas_alternativa_pergunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='referencia_biblica',
            field=models.BooleanField(default=True),
        ),
    ]
