# Generated by Django 3.2.25 on 2024-05-31 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0008_pergunta_referencia_biblica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pergunta',
            old_name='revisado_em',
            new_name='aprovado_em',
        ),
        migrations.RenameField(
            model_name='pergunta',
            old_name='revisado_por',
            new_name='aprovado_por',
        ),
        migrations.RenameField(
            model_name='pergunta',
            old_name='revisado_status',
            new_name='aprovado_status',
        ),
    ]
