# Generated by Django 3.2.25 on 2024-05-31 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0009_auto_20240531_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='publicado_status',
            field=models.BooleanField(default=False, verbose_name='Publicado'),
        ),
    ]
